"""Add refresh_token column, delete current_token_id to users table

Revision ID: 07a4a563e670
Revises: eb9a5e2f28a9
Create Date: 2026-01-29 19:08:26.446955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a4a563e670'
down_revision: Union[str, Sequence[str], None] = 'eb9a5e2f28a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.drop_column('users', 'current_token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_token_id', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
