"""Initial tables

Revision ID: eb9a5e2f28a9
Revises: 
Create Date: 2026-01-23 22:58:35.505444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9a5e2f28a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('default_units', sa.Enum('METRIC', 'IMPERIAL', 'KELVIN', name='metric'), nullable=False),
    sa.Column('preferred_lang', sa.String(length=10), nullable=False),
    sa.Column('current_token_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_default_units', 'users', ['default_units'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_last_login', 'users', ['last_login_at'], unique=False)
    op.create_index('idx_user_preferred_lang', 'users', ['preferred_lang'], unique=False)
    op.create_index('idx_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('idx_user_username_active', 'users', ['username', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_default_units'), 'users', ['default_units'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('auth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', name='provider'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_username', sa.String(length=100), nullable=True),
    sa.Column('profile_data', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_email', name='uq_provider_email'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_provider_id'),
    sa.UniqueConstraint('provider', 'provider_username', name='uq_provider_username')
    )
    op.create_index('idx_auth_provider_active', 'auth_providers', ['provider', 'unlinked_at'], unique=False)
    op.create_index('idx_auth_user_provider', 'auth_providers', ['user_id', 'provider'], unique=False)
    op.create_index(op.f('ix_auth_providers_provider'), 'auth_providers', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_providers_provider_id'), 'auth_providers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_auth_providers_user_id'), 'auth_providers', ['user_id'], unique=False)
    op.create_table('saved_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone_offset', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'latitude', 'longitude', name='uq_user_coordinates'),
    sa.UniqueConstraint('user_id', 'location_name', 'country', name='uq_user_location_name')
    )
    op.create_index('idx_location_coords', 'saved_locations', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_location_name_country', 'saved_locations', ['location_name', 'country'], unique=False)
    op.create_index('idx_location_order', 'saved_locations', ['user_id', 'display_order'], unique=False)
    op.create_index('idx_location_user', 'saved_locations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_saved_locations_id'), 'saved_locations', ['id'], unique=False)
    op.create_index(op.f('ix_saved_locations_location_name'), 'saved_locations', ['location_name'], unique=False)
    op.create_index(op.f('ix_saved_locations_user_id'), 'saved_locations', ['user_id'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.Enum('OPENWEATHER', name='apiservice'), nullable=False),
    sa.Column('name_key', sa.String(length=100), nullable=True),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service', name='uq_user_service')
    )
    op.create_index('idx_user_service', 'user_api_keys', ['user_id', 'service', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_index('idx_user_service', table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_saved_locations_user_id'), table_name='saved_locations')
    op.drop_index(op.f('ix_saved_locations_location_name'), table_name='saved_locations')
    op.drop_index(op.f('ix_saved_locations_id'), table_name='saved_locations')
    op.drop_index('idx_location_user', table_name='saved_locations')
    op.drop_index('idx_location_order', table_name='saved_locations')
    op.drop_index('idx_location_name_country', table_name='saved_locations')
    op.drop_index('idx_location_coords', table_name='saved_locations')
    op.drop_table('saved_locations')
    op.drop_index(op.f('ix_auth_providers_user_id'), table_name='auth_providers')
    op.drop_index(op.f('ix_auth_providers_provider_id'), table_name='auth_providers')
    op.drop_index(op.f('ix_auth_providers_provider'), table_name='auth_providers')
    op.drop_index('idx_auth_user_provider', table_name='auth_providers')
    op.drop_index('idx_auth_provider_active', table_name='auth_providers')
    op.drop_table('auth_providers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_default_units'), table_name='users')
    op.drop_index('idx_user_username_active', table_name='users')
    op.drop_index('idx_user_role_active', table_name='users')
    op.drop_index('idx_user_preferred_lang', table_name='users')
    op.drop_index('idx_user_last_login', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_default_units', table_name='users')
    op.drop_index('idx_user_created', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
