FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ .

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ARG VITE_FRONTEND_OAUTH_CALLBACK_URL
ENV VITE_FRONTEND_OAUTH_CALLBACK_URL=$VITE_FRONTEND_OAUTH_CALLBACK_URL

RUN npm run build

FROM node:20-alpine AS runner
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/dist /app/dist

EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]
